### ISSUE TITLE
Eye icon is not working fine in Confirm Password field

### ISSUE THREAD

**Issue by lakshmi-d-27** [ravin-d-27/Timer_Website#1]
Eye icon is not working fine in Confirm Password field

Steps to reproduce:
Launch the URL
Click on Sign Up button.
Provide the values in the following fields:
a. User Name
b. Password
c. Confirm Password
and verify the eye icon functionality in Confirm password field
![image](https://github.com/ravin-d-27/Timer_Website/assets/144231441/fc9023b6-de2d-420d-a31a-34920db113cc)

**Comment by ravin-d-27** [comment]
Will resolve the issue soon !

**Comment by ravin-d-27** [comment]
This is not an issue; this is actually for security reasons. If a person gets inactive or gets away from the device, unauthorised person cannot find the show password button (eye icon).
